---
networks:
  <yournetwork>:
    external: true

services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/<replacepath>:/app/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dockhand.entrypoints=http,https'
      - 'traefik.http.routers.dockhand.rule=Host(`dockhand.<yourdomain>.<tld>`)'
      - 'traefik.http.services.dockhand.loadbalancer.server.port=3000'
      - 'traefik.http.routers.dockhand.service=dockhand'
      - 'traefik.http.routers.dockhand.tls=true'
      - 'traefik.http.routers.dockhand.tls.certresolver=prod'
      - "traefik.docker.network=<yournetwork>"
    networks:
      - <yournetwork>
