---
networks:
  app-network:
    external: true

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 400M
    volumes:
      - ~/docker/mealie/data/:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.<yourinternaldomain>
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_SERVER: $POSTGRES_SERVER
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mealie.entrypoints=http,https'
      - 'traefik.http.routers.mealie.rule=Host(`mealie.<yourinternaldomain>`)'
      - 'traefik.http.services.mealie.loadbalancer.server.port=9000'
      - 'traefik.http.routers.mealie.service=mealie'
      - 'traefik.http.routers.mealie.tls=true'
      - 'traefik.http.routers.mealie.tls.certresolver=prod'
    restart: unless-stopped
    networks:
      - app-network
