---
networks:
  app-network:
    external: true

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Paris
    volumes:
      - ~/homelab/ntfy/config/cache:/var/cache/ntfy
      - ~/homelab/ntfy/config/ntfy:/etc/ntfy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ntfy.entrypoints=http,https'
      - 'traefik.http.routers.ntfy.rule=Host(`ntfy.<yourinternaldomain>`) || Host(`ntfy.<yourexternaldomain>`)'
      - 'traefik.http.services.ntfy.loadbalancer.server.port=80'
      - 'traefik.http.routers.ntfy.service=ntfy'
      - 'traefik.http.routers.ntfy.tls=true'
      - 'traefik.http.routers.ntfy.tls.certresolver=prod'
    restart: unless-stopped
    networks:
      - app-network
