---
title: Homelab Homepage
theme: dark
color: slate
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

headerStyle: boxedWidgets
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

hideVersion: true
showStats: true
statusStyle: 'dot'

layout:
  Network:
    style: row
    columns: 2
    icon: mdi-network-#FFFFFF
  Resources:
    style: row
    columns: 2
    icon: mdi-package-variant-#FFFFFF
  Monitoring:
    style: row
    columns: 2
    icon: mdi-list-status-#FFFFFF
  Infrastructure and Data:
    style: row
    columns: 2
    icon: mdi-server-#FFFFFF
