---
networks:
  app-network:
    external: true

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - ~/docker/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.entrypoints=http,https'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.<yourinternaldomain>`)'
      - 'traefik.http.services.pgadmin.loadbalancer.server.port=80'
      - 'traefik.http.routers.pgadmin.service=pgadmin'
      - 'traefik.http.routers.pgadmin.tls=true'
      - 'traefik.http.routers.pgadmin.tls.certresolver=prod'
    restart: unless-stopped
    networks:
      - app-network

  postgres_central:
    image: postgres:17.2-alpine3.20
    container_name: postgres_central
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: root
    volumes:
      - ~/docker/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network